### ISSUE TITLE
influxdb-client-swift 2.0.2 Release v0.0.1

### ISSUE THREAD

**Issue by bednar** [influxdata/influxdb-client-swift#16]
# Client 

- **Platforms**: macOS, iOS, watchOS, tvOS, Linux
- **Swift**: 5.3+
- **Installation**: Swift Package Manager
- **Homepage**: https://github.com/bonitoo-io/influxdb-client-swift
- **API Docs**: https://bonitoo-io.github.io/influxdb-client-swift/

## API

1. Write API
    - The data could be written as: `String`, `Data Point`, `Tuple` and array of items 
    - Response handled as `(response, error)`, `Swift.Result` or `Combine`
    - **README.md**: https://github.com/bonitoo-io/influxdb-client-swift#writes
    - **API Docs**: https://bonitoo-io.github.io/influxdb-client-swift/Classes/WriteAPI.html
    - **WriteAPI.swift**: https://github.com/bonitoo-io/influxdb-client-swift/blob/master/Sources/InfluxDBSwift/WriteAPI.swift#L56
1. Query API
     - The data could be retrieved as: lazy sequence of `FluxRecord` or raw response as `Data`
     - Response handled as `(response, error)`, `Swift.Result` or `Combine`
     - **README.md**: https://github.com/bonitoo-io/influxdb-client-swift#queries
     - **API Docs**: https://bonitoo-io.github.io/influxdb-client-swift/Classes/QueryAPI.html
     - **QueryAPI.swift**: https://github.com/bonitoo-io/influxdb-client-swift/blob/master/Sources/InfluxDBSwift/QueryAPI.swift#L62
1. Delete API
     - The DeleteAPI supports deletes points from an InfluxDB bucket. 
     - Response handled as `(response, error)`, `Swift.Result` or `Combine`
     - **README.md**: https://github.com/bonitoo-io/influxdb-client-swift#delete-data
     - **API Docs**: https://bonitoo-io.github.io/influxdb-client-swift/Classes/DeleteAPI.html
     - **DeleteAPI.swift**: https://github.com/bonitoo-io/influxdb-client-swift/blob/master/Sources/InfluxDBSwift/DeleteAPI.swift#L34
1. Management API
     - **README.md**: https://github.com/bonitoo-io/influxdb-client-swift#management-api
     - **API Docs**: https://bonitoo-io.github.io/influxdb-client-swift/Classes/InfluxDB2API.html

## Examples:

- [WriteData](https://github.com/bonitoo-io/influxdb-client-swift/tree/master/Examples/WriteData#writedata) - How to write data with different type of records 
- [QueryCpu](https://github.com/bonitoo-io/influxdb-client-swift/blob/master/Examples/QueryCpu#querycpu) - How to query data into sequence of `FluxRecord`
- [DeleteData](https://github.com/bonitoo-io/influxdb-client-swift/blob/master/Examples/DeleteData#deletedata) - How to delete data with specified predicate.
- [CreateNewBucket](https://github.com/bonitoo-io/influxdb-client-swift/blob/master/Examples/CreateNewBucket#createnewbucket) - How to create new bucket with permission to write 

https://github.com/bonitoo-io/influxdb-client-swift/tree/master/Examples

## Advanced Usage:

- [InfluxDB 1.8 API compatibility](https://github.com/bonitoo-io/influxdb-client-swift#influxdb-18-api-compatibility)
- [Default Tags](https://github.com/bonitoo-io/influxdb-client-swift#default-tags)

**Comment by bednar** [comment]
Hi All,

I've prepared a short summary about `influxdb-client-swift` for a review before first release. ⬆️

Could you look at this? 

**Any feedback is welcome and helpful.** 

Regards

cc @rhajek, @ivankudibal, @sranka, @vlastahajek, @rolincova

**Comment by sranka** [comment]
The summary looks good, I also randomly inspected the target links
-  https://github.com/bonitoo-io/influxdb-client-swift#queries - a link to FluxRecord is broken
-  the query that returns cursor of FluxRecords is fine, it is however not possible to observe table metadata (what is the group key? did the table change with the last record?)

**Comment by bednar** [comment]
> * https://github.com/bonitoo-io/influxdb-client-swift#queries - a link to FluxRecord is broken

Fixed

> * the query that returns cursor of FluxRecords is fine, it is however not possible to observe table metadata (what is the group key? did the table change with the last record?)

It was a purpose. I want to simplify API to users, but internally CSV Parser uses `(table: QueryAPI.FluxTable, record: QueryAPI.FluxRecord)`: https://github.com/bonitoo-io/influxdb-client-swift/blob/3bc578e4f891a870bb5a4ae086ef6f3834e1245b/Sources/InfluxDBSwift/FluxCSVParser.swift#L25

**Comment by bednar** [comment]
Hi @davidgs, 

we have prepared a first version of the `influxdb-client-swift`. Could you look at this? ⬆️ 

Any feedback is welcome and helpful.

Regards
