### ISSUE TITLE
Add example code snippet showing batching of writes

### ISSUE THREAD

**Issue by bckeene** [influxdata/influxdb-client-swift#43]
**Proposal:**
Under the [Swift Client Repo](https://github.com/influxdata/influxdb-client-swift/tree/master/Examples), please add an example showing writing batched data - similar to our approach with the Python Client.

**Use case:**
It's important for us to offer a reference example showing best practices associated with writing data so users can get up and running.

**Comment by bednar** [comment]
Closed by #44

**Comment by bckeene** [comment]
Thank you, @bednar
